"""add nullable metadata to columns

Revision ID: 2bb49269cb9f
Revises: b5a962390c8e
Create Date: 2026-02-27 20:25:31.421341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb49269cb9f'
down_revision = 'b5a962390c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    # ### end Alembic commands ###
