"""add link to wish model

Revision ID: b5a962390c8e
Revises: eb411965dcdc
Create Date: 2026-02-27 17:31:35.331941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a962390c8e'
down_revision = 'eb411965dcdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=4096), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
