"""wish table

Revision ID: eb411965dcdc
Revises: 22ac50f29945
Create Date: 2026-02-23 20:28:40.013239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb411965dcdc'
down_revision = '22ac50f29945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wish', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wish_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_wish_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wish_user_id'))
        batch_op.drop_index(batch_op.f('ix_wish_timestamp'))

    op.drop_table('wish')
    # ### end Alembic commands ###
